---
# molecule_exceptions:
#   - variation: alpine
#     reason: "Not idempotent"
molecule_scenarios:
  - scenario: "default"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "fedora35"
      - "fedora36"
      - "amazonlinux"
      - "amazonlinux2022"
      - "rockylinux8"
      - "almalinux8"
      - "almalinux9"
  - scenario: "custom_version"
    ansible: ["previous", "current"]
    platforms:
      - "debian10"
      - "debian11"
      - "ubuntu1804"
      - "ubuntu2004"
      - "ubuntu2204"
      - "centos7"
      - "centos-stream8"
      - "centos-stream9"
      - "ubi8"
      - "fedora35"
      - "fedora36"
      - "amazonlinux"
      - "amazonlinux2022"
      - "rockylinux8"
      - "almalinux8"
      - "almalinux9"
