---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    rclone_release: "custom"
    rclone_version: '1.58.0'
    rclone_conf_path: "~/.config/rclone"
    rclone_config:
      - name: "WebDAV"
        options:
          - "type = webdav"
          - "url = https://nextcloud.domain.tld/remote.php/dav/files/username/"
          - "vendor = nextcloud"
          - "user = username"
          - "bearer_token = SuperSecretToken"

  roles:
    - role: "ansible-role-rclone"
