---
- name: Verify
  hosts: all
  become: true
  gather_facts: true
  vars:
    rclone_version: '1.58.0'

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check if rclone installed
      ansible.builtin.stat:
        path: "/usr/local/bin/rclone"
      check_mode: true
      register: verify_rclone_is_installed
      failed_when: not verify_rclone_is_installed.stat.exists

    - name: compare installed version with expected version
      ansible.builtin.command: "/usr/local/bin/rclone --version"
      check_mode: true
      register: rclone_current_version
      failed_when: rclone_version not in rclone_current_version.stdout

    - name: check /etc/rclone directory
      ansible.builtin.file:
        path: "~/.config/rclone"
        state: directory
        owner: "root"
        group: "root"
        mode: "0750"
      check_mode: true
      register: verify_rclone_conf_folder
      failed_when: (verify_rclone_conf_folder is changed) or (verify_rclone_conf_folder is failed)

    - name: check rclone config file
      ansible.builtin.lineinfile:
        name: "~/.config/rclone/rclone.conf"
        line: "# Ansible managed: Do NOT edit this file manually!"
        state: present
        owner: "root"
        group: "root"
        mode: "0600"
      check_mode: true
      register: verify_rclone_config
      failed_when: (verify_rclone_config is changed) or (verify_rclone_config is failed)
