---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: SmokeTests
      ansible.builtin.debug:
        msg:
          - "ansible_version => {{ansible_version}}"
          - "ansible_distribution => {{ ansible_distribution }}"
          - "ansible_distribution_major_version => {{ ansible_distribution_major_version }}"
          - "ansible_os_family  => {{ ansible_os_family}}"
          - "ansible_system  => {{ ansible_system }}"

    - name: Check if rclone installed
      ansible.builtin.stat:
        path: "/usr/local/bin/rclone"
      check_mode: true
      register: verify_rclone_is_installed
      failed_when: not verify_rclone_is_installed.stat.exists
